### ISSUE TITLE
R xml2 Code generated gives wrong x arg

### ISSUE THREAD

**Issue by eduardszoecs** [hrbrmstr/xmlview#8]
e.g. if I exec on a object not named `doc`

```
library(xml2)
library(xmlview)
txt <- paste0("<note><to>Tove</to><from>Jani</from><heading>Reminder</heading>",
              "<body>Don't forget me this weekend!</body></note>")
xxx <- read_xml(txt)
xml_view(xxx, add_filter = TRUE)
```

it returns as R xml2 Code:

```
xml2::xml_find_all(doc, './/to', ns=xml2::xml_ns(doc))
```

however it should be

```
xml2::xml_find_all(xxx, './/to', ns=xml2::xml_ns(xxx))
```

**Comment by hrbrmstr** [comment]
I was wondering when someone wld make that request :-) I'll add it to the
TODO (it's hardocded to `doc` right now but it's not difficult to change. I
may add a an option to do away with the `xml2::` prefixes as well (though
they don't hurt).

**Comment by hrbrmstr** [comment]
Nascent support for this is now in the latest push. Of note: the generated R code truly only makes sense when an `xml_document` is passed in and was provided mostly as an "icing on the cake" feature. It's unlikely I'll be providing any enhancements outside of this basic feature (but it was a needed feature IMO).
